[package]
name = "sudoku-solver"
version = "0.1.0"
edition = "2021"

[lib]
name = "sudoku"
path = "src/lib.rs"


[dependencies]
ndarray = "0.15.4"
clap = { version = "3.1.12", features = ["derive"] }
colored = "2.0.0"

